# Generated by Django 3.1.13 on 2024-05-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersgroup',
            name='company',
        ),
    ]
