# Generated by Django 3.1.13 on 2024-05-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('our_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('saturday', models.BooleanField(default=False, verbose_name='Saturday')),
                ('sunday', models.BooleanField(default=False, verbose_name='Sunday')),
                ('monday', models.BooleanField(default=False, verbose_name='Monday')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Tuesday')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Wednesday')),
                ('thursday', models.BooleanField(default=False, verbose_name='Thursday')),
                ('friday', models.BooleanField(default=False, verbose_name='Friday')),
                ('all_days', models.BooleanField(default=False, verbose_name='All Days')),
                ('hours_to_notify', models.IntegerField(verbose_name='Hours To Notify')),
                ('notify_type', models.CharField(choices=[('1', 'System Default Notify'), ('4', 'Popup Message'), ('3', 'Custom Default Notify'), ('2', 'Marquee')], max_length=50, verbose_name='Type of Notification')),
                ('num_of_messages', models.IntegerField(verbose_name='Number of Messages to Show')),
                ('every_seconds', models.IntegerField(verbose_name='Every  Seconds')),
                ('gl_placement_from', models.CharField(choices=[('top', 'top'), ('bottom', 'bottom')], default='top', max_length=50, verbose_name='Placement From')),
                ('gl_placement_align', models.CharField(choices=[('right', 'right'), ('left', 'left')], default='right', max_length=50, verbose_name='Placement Align')),
                ('gl_animate_enter', models.CharField(choices=[('fadeInRight', 'fadeInRight'), ('bounceInDown', 'bounceInDown'), ('bounceIn', 'bounceIn'), ('flipInY', 'flipInY'), ('lightSpeedIn', 'lightSpeedIn'), ('rollIn', 'rollIn'), ('zoomInDown', 'zoomInDown')], default='fadeInRight', max_length=50, verbose_name='Animate Enter')),
                ('gl_animate_exit', models.CharField(choices=[('fadeOutRight', 'fadeOutRight'), ('bounceOutUp', 'bounceOutUp'), ('bounceOut', 'bounceOut'), ('flipOutX', 'flipOutX'), ('lightSpeedOut', 'lightSpeedOut'), ('rollOut', 'rollOut'), ('zoomInDown', 'zoomInDown'), ('zoomOutUp', 'zoomOutUp')], default='fadeOutRight', max_length=50, verbose_name='Animate Exit')),
                ('allow_dismiss', models.BooleanField(default=False, verbose_name='Allow Dismiss')),
                ('gl_newest_on_top', models.BooleanField(default=False, verbose_name='Newest on Top')),
                ('company', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='our_core.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Notification',
            },
        ),
    ]
