# Generated by Django 3.1.13 on 2024-05-24 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('our_notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationvariables',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificationvariables_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationvariables',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificationvariables_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
