# Generated by Django 3.1.13 on 2024-05-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_notifications', '0002_auto_20240524_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationvariables',
            name='company',
        ),
    ]
