# Generated by Django 5.0.6 on 2024-06-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=100, null=True, verbose_name='full name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='phone')),
                ('qualification', models.CharField(blank=True, choices=[('d', 'دكتوراه'), ('ms', 'ماجستير'), ('pk', 'بكالريوس'), ('dp', 'دبلوم')], max_length=100, null=True, verbose_name='qualification')),
                ('date_qualification', models.DateField(blank=True, null=True, verbose_name='date qualification')),
                ('field_study', models.CharField(blank=True, max_length=100, null=True, verbose_name='field study')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='date start')),
                ('name_job', models.CharField(choices=[('1', 'مدرب ب'), ('2', 'مدرب أ'), ('مدرب اول ب', '3'), ('مدرب اول أ', '4'), ('كبير المدربين', '5')], default='3', max_length=50, verbose_name='name')),
                ('off_addrs', models.CharField(blank=True, max_length=100, null=True, verbose_name='offes address')),
                ('Cuntry_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configration.cuntry')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
    ]
