# Generated by Django 5.0.6 on 2024-06-09 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0003_building_unit_name_subject_hours_subject_testing'),
        ('init_input', '0003_alter_trainer_user_alter_trainer_name_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('2', 'مدرب أ'), ('مدرب اول ب', '3'), ('مدرب اول أ', '4'), ('كبير المدربين', '5')], default='3', max_length=50, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('semester', models.CharField(choices=[('first', 'First semester'), ('second', 'Second semester')], default='first', max_length=10, verbose_name='Semester')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='reference')),
                ('projram', models.CharField(choices=[('evening', 'evening'), ('morning', 'morning')], default='morning', max_length=20, verbose_name='projram')),
                ('Calculated', models.BooleanField(default=True, verbose_name='calculated')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configration.subject')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='init_input.trainer')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
    ]
