# Generated by Django 5.0.6 on 2024-06-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0004_alter_trainer_name_job_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('مدرب أ', '2'), ('مدرب اول ب', '3'), ('مدرب اول أ', '4'), ('5', 'كبير المدربين')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
