# Generated by Django 5.0.6 on 2024-06-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0005_alter_trainer_name_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('2', 'مدرب أ'), ('3', 'مدرب اول ب'), ('4', 'مدرب اول أ'), ('5', 'كبير المدربين')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
