# Generated by Django 5.0.6 on 2024-06-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0009_rename_calculated_tracking_calculated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={},
        ),
        migrations.AddField(
            model_name='tracking',
            name='name',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('مدرب أ', '2'), ('مدرب اول ب', '3'), ('4', 'مدرب اول أ'), ('5', 'كبير المدربين')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
