# Generated by Django 5.0.6 on 2024-06-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0011_rename_name_tracking_year_alter_trainer_name_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='projram',
            field=models.CharField(choices=[('evening', 'evening'), ('morning', 'morning')], default='morning', max_length=20, verbose_name='projram'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='semester',
            field=models.CharField(choices=[('01', 'First semester'), ('02', 'Second semester')], default='first', max_length=10, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('1', 'مدرب ب'), ('2', 'مدرب أ'), ('3', 'مدرب اول ب'), ('4', 'مدرب اول أ'), ('كبير المدربين', '5')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
