# Generated by Django 5.0.6 on 2024-06-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0012_alter_tracking_projram_alter_tracking_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='semester',
            field=models.CharField(choices=[('01', 'First semester'), ('02', 'Second semester')], default='01', max_length=10, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('مدرب أ', '2'), ('مدرب اول ب', '3'), ('4', 'مدرب اول أ'), ('5', 'كبير المدربين')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
