# Generated by Django 5.0.6 on 2024-06-22 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0013_alter_tracking_semester_alter_trainer_name_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('مدرب أ', '2'), ('مدرب اول ب', '3'), ('مدرب اول أ', '4'), ('5', 'كبير المدربين')], default='3', max_length=50, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='DetailsTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('count_student', models.IntegerField(default=0, verbose_name='count student')),
                ('max_mark', models.IntegerField(default=0, verbose_name='max mark')),
                ('min_mark', models.IntegerField(default=0, verbose_name='min mark')),
                ('absent', models.IntegerField(default=0, verbose_name='absent')),
                ('less_than', models.IntegerField(default=0, verbose_name='less than')),
                ('mark', models.IntegerField(default=0, verbose_name='mark')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='init_input.tracking')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
    ]
