# Generated by Django 5.0.6 on 2024-06-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0014_alter_trainer_name_job_detailstracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailstracking',
            name='tracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='init_input.tracking'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('1', 'مدرب ب'), ('مدرب أ', '2'), ('3', 'مدرب اول ب'), ('4', 'مدرب اول أ'), ('5', 'كبير المدربين')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
