# Generated by Django 5.0.6 on 2024-06-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0015_alter_detailstracking_tracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='semester',
            field=models.CharField(choices=[('02', 'Second semester'), ('01', 'First semester')], default='01', max_length=10, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('2', 'مدرب أ'), ('مدرب اول ب', '3'), ('4', 'مدرب اول أ'), ('كبير المدربين', '5')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
