# Generated by Django 5.0.6 on 2024-06-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0016_alter_tracking_semester_alter_trainer_name_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('1', 'مدرب ب'), ('مدرب أ', '2'), ('مدرب اول ب', '3'), ('مدرب اول أ', '4'), ('كبير المدربين', '5')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
