# Generated by Django 5.0.6 on 2024-07-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0019_alter_trainer_name_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='semester',
            field=models.CharField(choices=[('01', 'First semester'), ('02', 'Second semester')], default='01', max_length=10, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('2', 'مدرب أ'), ('مدرب اول ب', '3'), ('4', 'مدرب اول أ'), ('5', 'كبير المدربين')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
