# Generated by Django 5.0.6 on 2024-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0020_alter_tracking_semester_alter_trainer_name_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='projram',
            field=models.CharField(choices=[('morning', 'morning'), ('evening', 'evening')], default='morning', max_length=20, verbose_name='projram'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='semester',
            field=models.CharField(choices=[('02', 'Second semester'), ('01', 'First semester')], default='01', max_length=10, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('مدرب أ', '2'), ('3', 'مدرب اول ب'), ('مدرب اول أ', '4'), ('5', 'كبير المدربين')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
