# Generated by Django 5.0.6 on 2024-07-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0021_alter_tracking_projram_alter_tracking_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='projram',
            field=models.CharField(choices=[('evening', 'evening'), ('morning', 'morning')], default='morning', max_length=20, verbose_name='projram'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('1', 'مدرب ب'), ('2', 'مدرب أ'), ('3', 'مدرب اول ب'), ('4', 'مدرب اول أ'), ('كبير المدربين', '5')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
