# Generated by Django 5.0.6 on 2024-07-22 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0022_alter_subject_testing'),
        ('init_input', '0022_alter_tracking_projram_alter_trainer_name_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='semester',
            field=models.CharField(choices=[('01', 'First semester'), ('02', 'Second semester')], default='01', max_length=10, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('1', 'مدرب ب'), ('مدرب أ', '2'), ('3', 'مدرب اول ب'), ('4', 'مدرب اول أ'), ('كبير المدربين', '5')], default='3', max_length=50, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Note')),
                ('approval_file', models.FileField(blank=True, null=True, upload_to='approval', verbose_name='Approval')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configration.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configration.subject')),
                ('type_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configration.typefile')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
    ]
