# Generated by Django 5.0.6 on 2024-07-23 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0023_alter_subject_testing'),
        ('init_input', '0023_alter_tracking_semester_alter_trainer_name_job_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='semester',
            field=models.CharField(choices=[('02', 'Second semester'), ('01', 'First semester')], default='01', max_length=10, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('مدرب أ', '2'), ('مدرب اول ب', '3'), ('مدرب اول أ', '4'), ('كبير المدربين', '5')], default='3', max_length=50, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='SupervisoryVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('evaluation_for', models.CharField(choices=[('practical', 'practical'), ('theoretical', 'theoretical')], max_length=100, verbose_name='evaluation for')),
                ('Watched', models.BooleanField(default=False, verbose_name='watched')),
                ('Prepared', models.BooleanField(default=True, verbose_name='prepared')),
                ('semester', models.CharField(choices=[('02', 'Second semester'), ('01', 'First semester')], default='01', max_length=10, verbose_name='Semester')),
                ('date_start', models.DateField(verbose_name='date_start')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configration.section')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='init_input.trainer')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
    ]
