# Generated by Django 5.0.6 on 2024-07-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0024_alter_tracking_semester_alter_trainer_name_job_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisoryvisits',
            options={},
        ),
        migrations.RenameField(
            model_name='supervisoryvisits',
            old_name='Section',
            new_name='section',
        ),
        migrations.AddField(
            model_name='supervisoryvisits',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='projram',
            field=models.CharField(choices=[('morning', 'morning'), ('evening', 'evening')], default='morning', max_length=20, verbose_name='projram'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('2', 'مدرب أ'), ('مدرب اول ب', '3'), ('4', 'مدرب اول أ'), ('5', 'كبير المدربين')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
