# Generated by Django 5.0.6 on 2024-07-24 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0026_alter_supervisoryvisits_evaluation_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorevaluation',
            name='activities_1',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Contributes to the activities related to the trainees.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='activities_2',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Contributes to the activities related to the training environment.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='activities_3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Contributes to the activities related to the training course.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_1',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Presents the training objectives (cognitive, skill) of the curriculum at the beginning of each training period.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Uses training resources efficiently and effectively.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_11',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Uses e-learning techniques and appropriate training presentation tools.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_12',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Ensures the optimal use of training tools and e-learning systems.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_13',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Strives to develop his/her skills in using appropriate tools and modern technologies.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_14',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Innovating modern training methods for presenting the training course.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0)], verbose_name='Follows the rules and procedures of occupational health and safety.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_16',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0)], verbose_name='Ensures the cleanliness of the classroom or laboratory.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_17',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0)], verbose_name='Provides suggestions and solutions for safety problems.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0)], verbose_name='Operates and deals with equipment and machinery in a safe manner.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_19',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0)], verbose_name='Reports hazards and corrects dangerous practices and conditions.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_2',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Mastering the training course, its contents, and the related updated scientific facts, knowledge, skills, and basic references.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_20',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name="Identifies the trainees' levels at the beginning of the training semester."),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_21',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name="Follows up on the trainees' performance through records."),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_22',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Considers individual differences between trainees when conducting the evaluation.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_23',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Strives to develop trainees through continuous follow-up during the training semester and addressing deficiencies.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_24',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Follows multiple strategies in presenting the course to cover the cognitive levels of the trainees.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_25',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0)], verbose_name='Ensures the maintenance of devices and equipment in the workshop/laboratories.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_26',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0)], verbose_name='Observes the special instructions for maintaining devices and their operation.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_27',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0)], verbose_name='Develops methods of caring for the maintenance of equipment and training devices.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_3',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Presents the information and applies the skills related to the training course in a way that enables the trainee to comprehend and master it.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_4',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name="Contributes to enriching the training course, which positively reflects on the trainees' experiences."),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name="Is familiar with the institution's vision, mission, goals, and policies, and works to achieve them."),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Ability to manage trainees within the training place.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_7',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Distributing the training period time appropriately over the stages of the training material.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_8',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Uses various and modern training methods.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='competencies_9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Moves appropriately within the training place.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='development_1',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Strives to increase his/her knowledge and experience in his/her specialty field according to the available resources.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='development_2',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Participates in courses, workshops, lectures, and seminars in the field of specialization.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='development_3',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Contributes to transferring his/her experiences and what he/she has learned to his/her colleagues.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='development_4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Is familiar with the concept and importance of the course file and its benefits.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='development_5',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Fills out the approved forms related to the course file.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='development_6',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Organizes the course file in an appropriate manner.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Accepts guidance and discusses it if it is not well understood.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Balances between trainees.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_11',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='Preserves the dignity of the trainees and is aware of their rights.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_12',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name="Utilizes the trainees' time in a useful manner."),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_13',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name="Accepts the trainees' observations."),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_14',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Adheres to the work uniform.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_15',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Ensures a neat and clean appearance.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_16',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Adheres to official working hours (attendance, departure).'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_17',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Is present in his/her office according to the office hours schedule in the department.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_18',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Attends and participates in department meetings.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_19',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Adheres to the time allocated for the training periods (start, end).'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Builds good relationships with superiors to improve and develop work.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_20',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Follows the administrative procedures in case of absence or leaving the workplace before the end of the work shift.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_21',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Strives to complete the assigned tasks on time.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_22',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Observes the rules and regulations in carrying out his/her work.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_23',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Develops methods of completing the assigned tasks according to quality standards.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Can express himself/herself and explain his/her idea well.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Can be relied upon to perform other tasks.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Seeks to establish a good relationship with everyone.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Exchanges educational experiences with colleagues in a way that serves the training interest.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Takes the initiative to bring closer and strengthen positive relationships with colleagues.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Participates with his/her colleagues in carrying out joint work or activities.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Sets a good example for the trainees.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='planning_1',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.5)], verbose_name='There is a written and distributed plan over the weeks of the training semester.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='planning_2',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.5)], verbose_name='There is a commitment to the timetable of the plan.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name="Follows up on the trainees' work (assignments, exercises) and records the grades."),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Has the initiative to know the abilities, tendencies, and circumstances of the trainees he/she supervises.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_11',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name="Coordinates with the direct supervisor and the mentor to address the trainees' problems."),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_12',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Closely and accurately follows up on his/her trainees during the training semester and always seeks to provide them with advice and guidance.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_13',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name="Uses the trainee's performance follow-up record correctly."),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_14',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Provides effective assistance to each trainee to improve his/her training level.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_15',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name="Identifies the reasons for the trainees' academic failure."),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_16',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Strives to ensure that trainees have the ability to apply.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_17',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Analyzes the results of applications, tests, and observations using appropriate statistical methods.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_18',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Prepares a special file for his/her professional achievement according to the designated standards.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_19',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Fills out the approved forms related to the course file.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Conducts short exams on the course contents.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_20',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2)], verbose_name='Organizes the course file in an appropriate manner.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Analyzes the test results to address the deficiencies.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name="Diversifies the evaluation methods (oral, written, practical) in accordance with the nature of the training material, the trainees' abilities, and the available resources."),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Prepares comprehensive exams for the training curriculum according to scientific foundations.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Utilizes pre-assessment, formative, and summative evaluation methods to measure the achievement of objectives.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_7',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='Is familiar with the concept of vocational guidance and training counseling.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Is present in his/her office to guide the trainees.'),
        ),
        migrations.AlterField(
            model_name='instructorevaluation',
            name='productivity_9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Carries out the assigned tasks of training guidance and counseling for trainees in the department.'),
        ),
        migrations.AlterField(
            model_name='supervisoryvisits',
            name='evaluation_for',
            field=models.CharField(choices=[('practical', 'practical'), ('theoretical', 'theoretical')], max_length=100, verbose_name='evaluation for'),
        ),
        migrations.AlterField(
            model_name='supervisoryvisits',
            name='semester',
            field=models.CharField(choices=[('01', 'First semester'), ('02', 'Second semester')], default='01', max_length=10, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='semester',
            field=models.CharField(choices=[('01', 'First semester'), ('02', 'Second semester')], default='01', max_length=10, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('مدرب ب', '1'), ('2', 'مدرب أ'), ('3', 'مدرب اول ب'), ('4', 'مدرب اول أ'), ('كبير المدربين', '5')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
