# Generated by Django 5.0.6 on 2024-07-24 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_input', '0027_alter_instructorevaluation_activities_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorevaluation',
            name='personal_23',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Develops methods of completing the assigned tasks according to quality standards.'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='projram',
            field=models.CharField(choices=[('evening', 'evening'), ('morning', 'morning')], default='morning', max_length=20, verbose_name='projram'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name_job',
            field=models.CharField(choices=[('1', 'مدرب ب'), ('مدرب أ', '2'), ('3', 'مدرب اول ب'), ('4', 'مدرب اول أ'), ('5', 'كبير المدربين')], default='3', max_length=50, verbose_name='name'),
        ),
    ]
