# Generated by Django 5.0.6 on 2024-07-21 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configration', '0017_alter_building_unit_name_alter_subject_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='week name')),
                ('date', models.DateField(verbose_name='date')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('all_department', models.BooleanField(default=False, verbose_name='all department')),
                ('name_task', models.CharField(max_length=100, verbose_name='task')),
                ('note', models.CharField(blank=True, max_length=1000, null=True, verbose_name='note')),
                ('requred_file', models.BooleanField(default=False, verbose_name='requred file')),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks', verbose_name='file')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configration.department')),
                ('head_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configration.headdepartment')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('Week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.week')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
    ]
