# Generated by Django 5.0.6 on 2024-07-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_head_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='See_achievement',
            field=models.BooleanField(default=False, verbose_name='See the achievement'),
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False, verbose_name='done'),
        ),
    ]
