# Generated by Django 5.0.6 on 2024-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_see_achievement_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='See_achievement',
        ),
        migrations.AlterField(
            model_name='task',
            name='requred_file',
            field=models.BooleanField(default=False, verbose_name='See the achievement'),
        ),
    ]
