# Generated by Django 5.0.6 on 2024-07-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0023_alter_subject_testing'),
        ('todo', '0004_remove_task_see_achievement_alter_task_requred_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='configration.department'),
        ),
    ]
