# Generated by Django 5.0.6 on 2024-06-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(verbose_name='number')),
                ('name_building', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(verbose_name='number')),
                ('name_cuntry', models.CharField(max_length=25, verbose_name='name')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(verbose_name='number')),
                ('name_department', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(verbose_name='number')),
                ('name_section', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(verbose_name='number')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('name_subject', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(verbose_name='number')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
    ]
