# Generated by Django 5.0.6 on 2024-06-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='unit_name',
            field=models.CharField(choices=[('unit', 'كلية الرياض')], default='unit', max_length=10, verbose_name='unit trining'),
        ),
        migrations.AddField(
            model_name='subject',
            name='hours',
            field=models.IntegerField(default=1, verbose_name='hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('final', 'final test'), ('first', 'First test'), ('second', 'Second test')], default='first', max_length=10, verbose_name='testing'),
        ),
    ]
