# Generated by Django 5.0.6 on 2024-06-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0003_building_unit_name_subject_hours_subject_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='stage',
            field=models.CharField(choices=[('diploma', 'diploma'), ("Bachelor's", "Bachelor's")], default='diploma', max_length=100, verbose_name='stage'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('first', 'First test'), ('second', 'Second test'), ('final', 'final test')], default='first', max_length=10, verbose_name='testing'),
        ),
    ]
