# Generated by Django 5.0.6 on 2024-06-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0006_division_program_alter_subject_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='program',
            field=models.CharField(choices=[('morning', 'morning'), ('evening', 'evening')], default='morning', max_length=20, verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('second', 'Second test'), ('first', 'First test'), ('final', 'final test')], default='first', max_length=10, verbose_name='testing'),
        ),
    ]
