# Generated by Django 5.0.6 on 2024-06-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0007_alter_division_program_alter_subject_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('first', 'First test'), ('final', 'final test'), ('second', 'Second test')], default='first', max_length=10, verbose_name='testing'),
        ),
    ]
