# Generated by Django 5.0.6 on 2024-06-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0011_alter_division_program_alter_subject_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='stage',
            field=models.CharField(choices=[('diploma', 'diploma'), ("Bachelor's", "Bachelor's")], default='diploma', max_length=100, verbose_name='stage'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('second', 'Second test'), ('final', 'final test'), ('first', 'First test')], default='first', max_length=10, verbose_name='testing'),
        ),
    ]
