# Generated by Django 5.0.6 on 2024-06-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0012_alter_subject_stage_alter_subject_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='stage',
            field=models.CharField(choices=[("Bachelor's", "Bachelor's"), ('diploma', 'diploma')], default='diploma', max_length=100, verbose_name='stage'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('final', 'final test'), ('second', 'Second test'), ('first', 'First test')], default='first', max_length=10, verbose_name='testing'),
        ),
    ]
