# Generated by Django 5.0.6 on 2024-06-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0013_alter_subject_stage_alter_subject_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('second', 'Second test'), ('final', 'final test'), ('first', 'First test')], default='first', max_length=10, verbose_name='testing'),
        ),
    ]
