# Generated by Django 5.0.6 on 2024-07-21 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0016_alter_subject_stage_alter_subject_testing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='unit_name',
            field=models.CharField(choices=[('unit', 'Riyadh College')], default='unit', max_length=10, verbose_name='unit trining'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='stage',
            field=models.CharField(choices=[('diploma', 'diploma'), ("Bachelor's", "Bachelor's")], default='diploma', max_length=100, verbose_name='stage'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('final', 'final test'), ('first', 'First test'), ('second', 'Second test')], default='first', max_length=10, verbose_name='testing'),
        ),
        migrations.CreateModel(
            name='HeadDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='head department')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('print', 'can print'), ('view_sidbar', 'displaying in side bar'), ('app_view_permission', 'app view')],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configration.headdepartment'),
        ),
    ]
