# Generated by Django 5.0.6 on 2024-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0019_alter_subject_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='program',
            field=models.CharField(choices=[('morning', 'morning'), ('evening', 'evening')], default='morning', max_length=20, verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='stage',
            field=models.CharField(choices=[("Bachelor's", "Bachelor's"), ('diploma', 'diploma')], default='diploma', max_length=100, verbose_name='stage'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('second', 'Second test'), ('final', 'final test'), ('first', 'First test')], default='first', max_length=10, verbose_name='testing'),
        ),
    ]
