# Generated by Django 5.0.6 on 2024-07-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0021_alter_division_program_alter_subject_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('final', 'final test'), ('second', 'Second test'), ('first', 'First test')], default='first', max_length=10, verbose_name='testing'),
        ),
    ]
