# Generated by Django 5.0.6 on 2024-07-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0023_alter_subject_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='program',
            field=models.CharField(choices=[('morning', 'morning'), ('evening', 'evening')], default='morning', max_length=20, verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='stage',
            field=models.CharField(choices=[('diploma', 'diploma'), ("Bachelor's", "Bachelor's")], default='diploma', max_length=100, verbose_name='stage'),
        ),
    ]
