# Generated by Django 5.0.6 on 2024-07-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0024_alter_division_program_alter_subject_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('first', 'First test'), ('second', 'Second test'), ('final', 'final test')], default='first', max_length=10, verbose_name='testing'),
        ),
    ]
