# Generated by Django 5.0.6 on 2024-07-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0026_alter_subject_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='program',
            field=models.CharField(choices=[('evening', 'evening'), ('morning', 'morning')], default='morning', max_length=20, verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='testing',
            field=models.CharField(choices=[('second', 'Second test'), ('first', 'First test'), ('final', 'final test')], default='first', max_length=10, verbose_name='testing'),
        ),
    ]
