# Generated by Django 5.0.6 on 2024-06-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=1000)),
                ('title_en', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(max_length=200)),
                ('icon_left', models.CharField(blank=True, max_length=1000, null=True)),
                ('icon_right', models.CharField(blank=True, max_length=1000, null=True)),
                ('url_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_sub_parent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='our_core.sidebaritem')),
            ],
        ),
    ]
