# Generated by Django 3.1.13 on 2024-05-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, verbose_name='Number Code')),
                ('name_ar', models.CharField(max_length=50, unique=True, verbose_name='Arabic Name')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Foreign Name')),
            ],
            options={
                'verbose_name': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foreig Nmae')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('address_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Foreign Address')),
                ('first_line', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Head')),
                ('second_line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Second Head')),
                ('third_line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Third Head')),
                ('first_line_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foreign First Head')),
                ('second_line_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foreign Second Head')),
                ('third_line_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foreign Third Head')),
                ('specifiction', models.CharField(blank=True, max_length=100, null=True, verbose_name='specifiction')),
                ('website', models.URLField(blank=True, max_length=100, null=True, verbose_name='website')),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Number')),
                ('company_register', models.PositiveIntegerField(blank=True, null=True, verbose_name='company register')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone')),
                ('image', models.ImageField(blank=True, default='no_img/no_image.png', max_length=254, null=True, upload_to='branch/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Branch',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, verbose_name='Number Code')),
                ('name_ar', models.CharField(max_length=50, unique=True, verbose_name='Arabic Name')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Foreign Name')),
            ],
            options={
                'verbose_name': 'City',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foreign Name')),
                ('abbrivation_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Name')),
                ('abbrivation_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Foreign Name')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes')),
                ('tax_number', models.CharField(max_length=100, verbose_name='Tax Number')),
                ('image', models.ImageField(blank=True, default='no_img/no_image.png', upload_to='company/')),
            ],
            options={
                'verbose_name': 'company',
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Number')),
                ('document_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(blank=True, choices=[('1', 'اكسل'), ('2', 'csv')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Number')),
                ('document_name', models.CharField(max_length=100)),
                ('import_type', models.CharField(choices=[('1', 'أدخل سجلات جديدة'), ('2', 'تعديل على السجلات')], max_length=100)),
                ('file_type', models.CharField(blank=True, choices=[('1', 'اكسل'), ('2', 'csv')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SidebarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=1000)),
                ('title_en', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(max_length=200)),
                ('icon_left', models.CharField(blank=True, max_length=1000, null=True)),
                ('icon_right', models.CharField(blank=True, max_length=1000, null=True)),
                ('url_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_sub_parent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='our_core.sidebaritem')),
            ],
        ),
    ]
