# Generated by Django 3.1.13 on 2024-05-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_remove_usersgroup_company'),
        ('our_notifications', '0003_remove_notificationvariables_company'),
        ('our_core', '0002_auto_20240524_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='company',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='company',
        ),
        migrations.RemoveField(
            model_name='city',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
